### ISSUE TITLE
Reduce Install size issue by removing the module folder

### ISSUE THREAD

**Issue by ayonious** [scttcper/ts-wcwidth#4]
@scttcper thanks a lot for the package. By noticing that there is no dependency I installed it in my package 
[console-table-printer](https://www.npmjs.com/package/console-table-printer)

But after installing I realized there is some issues.

The install size is bigger than [wcwidth](https://www.npmjs.com/package/wcwidth)

After looking in the installed package I found out there is a folder called modules to including almost 99% same code. 

<img width="277" alt="headerTitle_test_ts_—_console-table-printer" src="https://user-images.githubusercontent.com/19285393/101284196-0ff6cf80-37df-11eb-8c4d-54ee621f8096.png">

These things can be optimized to make it I think 40% of install size as its currently.

**Comment by scttcper** [comment]
Hey i've cut a bunch out by dropping the sourcemaps that are mostly useless. The module entry point contains the same code but with es module exports making them easier to grab for things like rollup and webpack. It does double up size on disk when installed without being bundled

**Comment by scttcper** [comment]
@ayonious if you want install size to stay small i'd recommend using rollup/webpack to bundle your dependencies and minify like you would for the frontend.
